apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-test
  namespace: app-test
spec:
  selector:
    app: rabbitmq-test
  type: NodePort
  ports:
  - name: http
    port: 5672
    targetPort: 5672
    nodePort: 30402
    protocol: TCP
  - name: ui
    port: 15672
    targetPort: 15672
    nodePort: 30403
    protocol: TCP  
