apiVersion: v1
kind: Service
metadata:
  name: mssql-test
  namespace: hcm-test
spec:
  selector:
    app: mssql-test
  type: NodePort
  ports:
  - port: 1433
    targetPort: 1433
    nodePort: 30101
    protocol: TCP