apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-test-pv-volume
  namespace: hcm-test
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/redis-test/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-test-pv-claim
  namespace: hcm-test
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi